apiVersion: apps/v1
kind: Deployment
metadata:
  name: dem8s-deployment
spec:
  selector:
    matchLabels:
      team: backend
  replicas: 3
  template:
    metadata:
      labels:
        team: backend
    spec:
      containers:
      - name: podummy
        image: charmingruby/podummy:latest
        ports:
        - name: http
          containerPort: 8080