services:
  db:
    container_name: db
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pack
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pack"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    container_name: migrate
    image: migrate/migrate
    volumes:
      - ./db/migration:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://postgres:postgres@db:5432/pack?sslmode=disable",
        "up",
      ]
    depends_on:
      db:
        condition: service_healthy

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    environment:
      REST_SERVER_PORT: 3000
      POSTGRES_URL: "postgres://postgres:postgres@db:5432/pack?sslmode=disable"
    depends_on:
      - migrate
