name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.3
          cache: false

      - name: Install dependencies
        working-directory: app
        run: |
          go mod tidy

      - name: Install mockery
        run: |
          go install github.com/vektra/mockery/v2@latest
          echo "${HOME}/go/bin" >> $GITHUB_PATH

      - name: Run tests
        working-directory: app
        run: make test
